# Generated by Django 5.1.5 on 2025-01-30 14:23

import filetime.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(default=filetime.models.next_week_start, verbose_name='Дата начала')),
                ('end_date', models.DateField(default=filetime.models.next_week_end, verbose_name='Дата завершения')),
                ('file', models.FileField(upload_to='uploads/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Модель',
                'verbose_name_plural': 'Модели',
            },
        ),
    ]
