# Generated by Django 5.1.5 on 2025-02-02 13:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetime', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Предмет')),
                ('room', models.CharField(max_length=50, verbose_name='Кабинет')),
                ('teacher', models.CharField(max_length=100, verbose_name='ФИО преподавателя')),
                ('group', models.CharField(max_length=50, verbose_name='Группа')),
            ],
            options={
                'verbose_name': 'Lesson',
                'verbose_name_plural': 'Lessons',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(verbose_name='День')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'ordering': ['day'],
            },
        ),
        migrations.AlterModelOptions(
            name='filetime',
            options={'verbose_name': 'FileTime', 'verbose_name_plural': 'FileTimes'},
        ),
        migrations.AddField(
            model_name='filetime',
            name='schedule',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='filetime.schedule', verbose_name='Расписание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='ScheduleLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='Lesson order for the day (e.g. 1st period, 2nd period, etc.)', verbose_name='Order')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filetime.lesson', verbose_name='Lesson')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filetime.schedule', verbose_name='Schedule')),
            ],
            options={
                'verbose_name': 'Scheduled Lesson',
                'verbose_name_plural': 'Scheduled Lessons',
                'ordering': ['order'],
                'unique_together': {('schedule', 'order')},
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='lessons',
            field=models.ManyToManyField(related_name='schedules', through='filetime.ScheduleLesson', to='filetime.lesson', verbose_name='Пары'),
        ),
    ]
