# Generated by Django 5.1.5 on 2025-02-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetime', '0002_lesson_schedule_alter_filetime_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filetime',
            name='schedule',
        ),
        migrations.RemoveField(
            model_name='schedulelesson',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='schedulelesson',
            name='start_time',
        ),
        migrations.AddField(
            model_name='filetime',
            name='schedules',
            field=models.ManyToManyField(to='filetime.schedule', verbose_name='Расписание'),
        ),
    ]
