# Generated by Django 5.1.5 on 2025-02-16 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetime', '0003_remove_filetime_schedule_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetime',
            name='schedules',
            field=models.ManyToManyField(blank=True, null=True, to='filetime.schedule', verbose_name='Расписание'),
        ),
    ]
