# Generated by Django 5.1.5 on 2025-02-24 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filetime', '0004_alter_filetime_schedules'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='group',
        ),
        migrations.AddField(
            model_name='schedulelesson',
            name='group',
            field=models.CharField(default=1, max_length=50, verbose_name='Группа'),
            preserve_default=False,
        ),
    ]
