# Generated by Django 5.1.5 on 2025-02-24 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('filetime', '0005_remove_lesson_group_schedulelesson_group'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedulelesson',
            unique_together=set(),
        ),
    ]
